name: CI



on: [push, workflow_dispatch]



jobs:


  build:



    runs-on: windows-latest



    steps:


    - name: Download


      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip


    - name: Extract


      run: Expand-Archive ngrok.zip


    - name: Auth


      run: .\ngrok\ngrok.exe authtoken 2090pUhZA4i6bzG84lirTWreViF_6k4cx81BeaboHxcChNdYx


    - name: Enable TS


      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      
    - run: Enable-NetFirewallRule -Name "RemoteDesktop-UserMode-In-TCP

    - run:  REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f


    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)


    - name: Create Tunnel


      run: .\ngrok\ngrok.exe tcp 3389

